<%
    <!SelectedClasses:SelectedClass!>!resetIterator();

    while (<!SelectedClasses:SelectedClass!>!next()) {

      symbolTable.parseXml(<![$jac:path:home]\\temp\\Class[SelectedClasses:SelectedClass].xml!>);

      if (<!Class:UniqueId!>!scan(<![SelectedClasses:SelectedClass]!>) == true) {

        <!Class!>!alias("currentClass");
        <!JGenerateClass!>!execMethod("execute");

      } else {

      }
    }
%>